"""empty message

Revision ID: 20199c581a49
Revises: a12cc7136a82
Create Date: 2021-05-22 10:19:54.583571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20199c581a49'
down_revision = 'a12cc7136a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows_table',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'artist_id', 'start_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shows_table')
    # ### end Alembic commands ###
