"""empty message

Revision ID: 996ff5eb26e8
Revises: 96a7065526c7
Create Date: 2021-05-19 09:51:57.441389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '996ff5eb26e8'
down_revision = '96a7065526c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.drop_column('shows', 'Start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
