"""empty message

Revision ID: a4885e65c9d6
Revises: b3275e1099d5
Create Date: 2021-02-19 11:17:26.376375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4885e65c9d6'
down_revision = 'b3275e1099d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Start_time', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'Start_time')
    # ### end Alembic commands ###
