"""empty message

Revision ID: d3de086f1f53
Revises: c5a8c637f3c9
Create Date: 2021-05-19 09:17:23.443679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3de086f1f53'
down_revision = 'c5a8c637f3c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', sa.String(length=120), nullable=True))
    op.drop_column('shows', 'Start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Start_time', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###
